"""added settings columns to lecturer

Revision ID: 12910b52fe49
Revises: a1f876b9fa7b
Create Date: 2026-04-01 02:48:22.170137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12910b52fe49'
down_revision: Union[str, Sequence[str], None] = 'a1f876b9fa7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('admin_id', sa.String(), server_default='ADM-000', nullable=False))
    op.add_column('admins', sa.Column('permissions', sa.String(), nullable=True))
    op.create_index(op.f('ix_admins_admin_id'), 'admins', ['admin_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admins_admin_id'), table_name='admins')
    op.drop_column('admins', 'permissions')
    op.drop_column('admins', 'admin_id')
    # ### end Alembic commands ###
