"""added settings columns to lecturer

Revision ID: 6833b68dc20f
Revises: afd1cdcd2278
Create Date: 2026-03-31 02:40:21.876858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6833b68dc20f'
down_revision: Union[str, Sequence[str], None] = 'afd1cdcd2278'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_index(op.f('ix_user_preferences_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_qr_tokens_id'), table_name='qr_tokens')
    op.drop_index(op.f('ix_qr_tokens_token_value'), table_name='qr_tokens')
    op.drop_table('qr_tokens')
    op.create_index(op.f('ix_announcements_id'), 'announcements', ['id'], unique=False)
    op.create_index(op.f('ix_course_materials_id'), 'course_materials', ['id'], unique=False)
    op.add_column('lecturers', sa.Column('photo_path', sa.String(), nullable=True))
    op.add_column('lecturers', sa.Column('contact_no', sa.String(), nullable=True))
    op.add_column('lecturers', sa.Column('theme_preference', sa.String(), nullable=True))
    op.add_column('lecturers', sa.Column('notify_class_reminders', sa.Boolean(), nullable=True))
    op.add_column('lecturers', sa.Column('notify_assignment_deadlines', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lecturers', 'notify_assignment_deadlines')
    op.drop_column('lecturers', 'notify_class_reminders')
    op.drop_column('lecturers', 'theme_preference')
    op.drop_column('lecturers', 'contact_no')
    op.drop_column('lecturers', 'photo_path')
    op.drop_index(op.f('ix_course_materials_id'), table_name='course_materials')
    op.drop_index(op.f('ix_announcements_id'), table_name='announcements')
    op.create_table('qr_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('class_session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_value', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'EXPIRED', 'REVOKED', name='tokenstatus'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['class_session_id'], ['class_sessions.id'], name=op.f('qr_tokens_class_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('qr_tokens_pkey'))
    )
    op.create_index(op.f('ix_qr_tokens_token_value'), 'qr_tokens', ['token_value'], unique=True)
    op.create_index(op.f('ix_qr_tokens_id'), 'qr_tokens', ['id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('remind_class', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('remind_assignment', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('theme', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_preferences_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_preferences_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('user_preferences_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_user_preferences_id'), 'user_preferences', ['id'], unique=False)
    # ### end Alembic commands ###
