"""add requires_password_change to users

Revision ID: 6ab5ff393e8c
Revises: b829db46fd89
Create Date: 2026-04-07 03:41:04.487699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ab5ff393e8c'
down_revision: Union[str, Sequence[str], None] = 'b829db46fd89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('requires_password_change', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'requires_password_change')
    # ### end Alembic commands ###
