"""add semester_no fixed

Revision ID: 9ff3d95b75f2
Revises: 6ab5ff393e8c
Create Date: 2026-04-07 13:55:45.325551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ff3d95b75f2'
down_revision: Union[str, Sequence[str], None] = '6ab5ff393e8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('semester_no', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'semester_no')
    # ### end Alembic commands ###
