"""add_full_name_to_admin

Revision ID: afd1cdcd2278
Revises: d89c24fb9350
Create Date: 2026-03-03 01:05:32.323109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afd1cdcd2278'
down_revision: Union[str, Sequence[str], None] = 'd89c24fb9350'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('full_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_admins_full_name'), 'admins', ['full_name'], unique=False)
    op.add_column('students', sa.Column('full_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_students_full_name'), 'students', ['full_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_full_name'), table_name='students')
    op.drop_column('students', 'full_name')
    op.drop_index(op.f('ix_admins_full_name'), table_name='admins')
    op.drop_column('admins', 'full_name')
    # ### end Alembic commands ###
