"""add department_id to classrooms

Revision ID: c0ece22517b7
Revises: 9427e72593ea
Create Date: 2026-04-15 01:18:05.318329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0ece22517b7'
down_revision: Union[str, Sequence[str], None] = '9427e72593ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classrooms', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'classrooms', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'classrooms', type_='foreignkey')
    op.drop_column('classrooms', 'department_id')
    # ### end Alembic commands ###
